[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "mojo-playground"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = """mojo -I . tests/test_async.mojo \
  && mojo -I . tests/test_bytes.mojo \
  && mojo -I . tests/test_closures.mojo \
  && mojo -I . tests/test_compile.mojo \
  && mojo -I . tests/test_contextmanagers.mojo \
  && mojo -I . tests/test_dicts.mojo \
  && mojo -I . tests/test_geom.mojo \
  && mojo -I . tests/test_gpu.mojo \
  && mojo -I . tests/test_hash.mojo \
  && mojo -I . tests/test_interop.mojo \
  && mojo -I . tests/test_iterators.mojo \
  && mojo -I . tests/test_linkedlist.mojo \
  && mojo -I . tests/test_mem.mojo \
  && mojo -I . tests/test_mlir.mojo \
  && mojo -I . tests/test_origins.mojo \
  && mojo -I . tests/test_sort.mojo \
  && mojo -I . tests/test_strings.mojo \
  && mojo -I . tests/test_sys.mojo \
  && mojo -I . tests/test_traits.mojo"""

[dependencies]
mojo = ">0.25.6.0.dev2025090505,<1"
