[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "mojo-playground"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">0.25.6.0.dev2025090505,<1"
